### ISSUE TITLE
Elk-pi

### ISSUE THREAD

**Issue by Nickgonzales76017** [elk-audio/elkpi-sdk#6] opened 2021-11-24 21:50 UTC
Hello, I was able to fully compile and load my plugin into sushi yesterday but at some point sushi crashed and ever since rebooting I can not load the plugin. I keep getting this error as a result.
any information would be greatly appreciated.
![proof](https://user-images.githubusercontent.com/45552585/143317216-63318e87-7127-46e4-8a4f-df47bbcb89ca.PNG)

**Comment by IliasBergstrom** [comment] 2021-11-25 09:16
Hi!

Since that is not a bug of the SDK, but the fact that your plugin is not finding a library it depends on, could you please post this in our forum?

I will close this issue, and will answer there.

Best,
Ilias of Elk

**Closed as completed by IliasBergstrom** 2021-11-25 09:16 UTC

**Comment by stez-mind** [comment] 2021-11-25 10:55
Hi @Nickgonzales76017 ,
the issue here is that you're running SUSHI as sudo (any specific reason for that?).

User mind has specified the environment variable:
LD_LIBRARY_PATH=/usr/xenomai/lib

that is required to run SUSHI with the Raspa / Xenomai frontend.

If you really need to run SUSHI as sudo (which I wouldn't recommend), you can just prepend that env. variable definition after sudo in your command line.
